- name: Docker Image Build and Push
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t jjang2da/cicdproject:"{{ lookup('env', 'BUILD_NUMBER') }}" java-hello-world/
    - command: docker login -u jjang2da -p "{{ lookup('env', 'TOKEN') }}"
    - command: docker push jjang2da/cicdproject:"{{ lookup('env', 'BUILD_NUMBER') }}"
    - command: docker logout
